# Generated by Django 2.1.5 on 2019-03-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='budget',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name='job',
            name='finalization_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(error_messages={'unique': 'Ya existe un trabajo con este título'}, max_length=200, null=True, unique=True),
        ),
    ]
