# Generated by Django 2.1.5 on 2019-03-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.IntegerField(choices=[(1, 'unassigned'), (2, 'assigned'), (-1, 'cancelled')], default=1),
        ),
    ]
