# Generated by Django 2.1.5 on 2019-05-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='budget',
            field=models.IntegerField(null=True),
        ),
    ]
