# Generated by Django 2.1.5 on 2019-06-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20190528_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.IntegerField(choices=[(1, 'unassigned'), (2, 'assigned'), (-1, 'cancelled'), (3, 'completed')], default=1),
        ),
    ]
